name: Wazuh CI/CD Pipeline GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Test Wazuh configuration
      run: |
        docker-compose up -d
        # Añade comandos para probar la configuración de Wazuh aquí

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Deploy new detection rules
      run: |
        docker-compose up -d
        # Añade comandos para desplegar nuevas reglas de detección aquí

